/*
Tinybeans API - Unofficial

Reverse Engineered API for Tinybeans.  This is horribly incomplete, and not supported

API version: 0.1.1
Contact: dave@mudsite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tinybeans

import (
	"encoding/json"
)

// DateStyle struct for DateStyle
type DateStyle struct {
	Format *string `json:"format,omitempty"`
	Label *string `json:"label,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewDateStyle instantiates a new DateStyle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDateStyle() *DateStyle {
	this := DateStyle{}
	return &this
}

// NewDateStyleWithDefaults instantiates a new DateStyle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDateStyleWithDefaults() *DateStyle {
	this := DateStyle{}
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *DateStyle) GetFormat() string {
	if o == nil || isNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DateStyle) GetFormatOk() (*string, bool) {
	if o == nil || isNil(o.Format) {
    return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *DateStyle) HasFormat() bool {
	if o != nil && !isNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *DateStyle) SetFormat(v string) {
	o.Format = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *DateStyle) GetLabel() string {
	if o == nil || isNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DateStyle) GetLabelOk() (*string, bool) {
	if o == nil || isNil(o.Label) {
    return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *DateStyle) HasLabel() bool {
	if o != nil && !isNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *DateStyle) SetLabel(v string) {
	o.Label = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *DateStyle) GetName() string {
	if o == nil || isNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DateStyle) GetNameOk() (*string, bool) {
	if o == nil || isNil(o.Name) {
    return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *DateStyle) HasName() bool {
	if o != nil && !isNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *DateStyle) SetName(v string) {
	o.Name = &v
}

func (o DateStyle) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !isNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !isNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableDateStyle struct {
	value *DateStyle
	isSet bool
}

func (v NullableDateStyle) Get() *DateStyle {
	return v.value
}

func (v *NullableDateStyle) Set(val *DateStyle) {
	v.value = val
	v.isSet = true
}

func (v NullableDateStyle) IsSet() bool {
	return v.isSet
}

func (v *NullableDateStyle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDateStyle(val *DateStyle) *NullableDateStyle {
	return &NullableDateStyle{value: val, isSet: true}
}

func (v NullableDateStyle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDateStyle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


