/*
Tinybeans API - Unofficial

Reverse Engineered API for Tinybeans.  This is horribly incomplete, and not supported

API version: 0.0.1
Contact: dave@mudsite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tinybeans

import (
	"encoding/json"
)

// CoverTheme struct for CoverTheme
type CoverTheme struct {
	Name *string `json:"name,omitempty"`
	Label *string `json:"label,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewCoverTheme instantiates a new CoverTheme object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoverTheme() *CoverTheme {
	this := CoverTheme{}
	return &this
}

// NewCoverThemeWithDefaults instantiates a new CoverTheme object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoverThemeWithDefaults() *CoverTheme {
	this := CoverTheme{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CoverTheme) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverTheme) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CoverTheme) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CoverTheme) SetName(v string) {
	o.Name = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *CoverTheme) GetLabel() string {
	if o == nil || o.Label == nil {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverTheme) GetLabelOk() (*string, bool) {
	if o == nil || o.Label == nil {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *CoverTheme) HasLabel() bool {
	if o != nil && o.Label != nil {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *CoverTheme) SetLabel(v string) {
	o.Label = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *CoverTheme) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoverTheme) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *CoverTheme) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *CoverTheme) SetUrl(v string) {
	o.Url = &v
}

func (o CoverTheme) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Label != nil {
		toSerialize["label"] = o.Label
	}
	if o.Url != nil {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableCoverTheme struct {
	value *CoverTheme
	isSet bool
}

func (v NullableCoverTheme) Get() *CoverTheme {
	return v.value
}

func (v *NullableCoverTheme) Set(val *CoverTheme) {
	v.value = val
	v.isSet = true
}

func (v NullableCoverTheme) IsSet() bool {
	return v.isSet
}

func (v *NullableCoverTheme) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoverTheme(val *CoverTheme) *NullableCoverTheme {
	return &NullableCoverTheme{value: val, isSet: true}
}

func (v NullableCoverTheme) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoverTheme) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


