/*
Tinybeans API - Unofficial

Reverse Engineered API for Tinybeans.  This is horribly incomplete, and not supported

API version: 0.0.1
Contact: dave@mudsite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package tinybeans

import (
	"encoding/json"
)

// AuthenticateRequst struct for AuthenticateRequst
type AuthenticateRequst struct {
	ClientId *string `json:"clientId,omitempty"`
	DeviceId *string `json:"deviceId,omitempty"`
	InviteToken *string `json:"inviteToken,omitempty"`
	Password *string `json:"password,omitempty"`
	RememberMe *bool `json:"rememberMe,omitempty"`
	Username *string `json:"username,omitempty"`
}

// NewAuthenticateRequst instantiates a new AuthenticateRequst object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticateRequst() *AuthenticateRequst {
	this := AuthenticateRequst{}
	return &this
}

// NewAuthenticateRequstWithDefaults instantiates a new AuthenticateRequst object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticateRequstWithDefaults() *AuthenticateRequst {
	this := AuthenticateRequst{}
	return &this
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *AuthenticateRequst) GetClientId() string {
	if o == nil || o.ClientId == nil {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticateRequst) GetClientIdOk() (*string, bool) {
	if o == nil || o.ClientId == nil {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *AuthenticateRequst) HasClientId() bool {
	if o != nil && o.ClientId != nil {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *AuthenticateRequst) SetClientId(v string) {
	o.ClientId = &v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *AuthenticateRequst) GetDeviceId() string {
	if o == nil || o.DeviceId == nil {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticateRequst) GetDeviceIdOk() (*string, bool) {
	if o == nil || o.DeviceId == nil {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *AuthenticateRequst) HasDeviceId() bool {
	if o != nil && o.DeviceId != nil {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *AuthenticateRequst) SetDeviceId(v string) {
	o.DeviceId = &v
}

// GetInviteToken returns the InviteToken field value if set, zero value otherwise.
func (o *AuthenticateRequst) GetInviteToken() string {
	if o == nil || o.InviteToken == nil {
		var ret string
		return ret
	}
	return *o.InviteToken
}

// GetInviteTokenOk returns a tuple with the InviteToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticateRequst) GetInviteTokenOk() (*string, bool) {
	if o == nil || o.InviteToken == nil {
		return nil, false
	}
	return o.InviteToken, true
}

// HasInviteToken returns a boolean if a field has been set.
func (o *AuthenticateRequst) HasInviteToken() bool {
	if o != nil && o.InviteToken != nil {
		return true
	}

	return false
}

// SetInviteToken gets a reference to the given string and assigns it to the InviteToken field.
func (o *AuthenticateRequst) SetInviteToken(v string) {
	o.InviteToken = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *AuthenticateRequst) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticateRequst) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *AuthenticateRequst) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *AuthenticateRequst) SetPassword(v string) {
	o.Password = &v
}

// GetRememberMe returns the RememberMe field value if set, zero value otherwise.
func (o *AuthenticateRequst) GetRememberMe() bool {
	if o == nil || o.RememberMe == nil {
		var ret bool
		return ret
	}
	return *o.RememberMe
}

// GetRememberMeOk returns a tuple with the RememberMe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticateRequst) GetRememberMeOk() (*bool, bool) {
	if o == nil || o.RememberMe == nil {
		return nil, false
	}
	return o.RememberMe, true
}

// HasRememberMe returns a boolean if a field has been set.
func (o *AuthenticateRequst) HasRememberMe() bool {
	if o != nil && o.RememberMe != nil {
		return true
	}

	return false
}

// SetRememberMe gets a reference to the given bool and assigns it to the RememberMe field.
func (o *AuthenticateRequst) SetRememberMe(v bool) {
	o.RememberMe = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *AuthenticateRequst) GetUsername() string {
	if o == nil || o.Username == nil {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticateRequst) GetUsernameOk() (*string, bool) {
	if o == nil || o.Username == nil {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *AuthenticateRequst) HasUsername() bool {
	if o != nil && o.Username != nil {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *AuthenticateRequst) SetUsername(v string) {
	o.Username = &v
}

func (o AuthenticateRequst) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ClientId != nil {
		toSerialize["clientId"] = o.ClientId
	}
	if o.DeviceId != nil {
		toSerialize["deviceId"] = o.DeviceId
	}
	if o.InviteToken != nil {
		toSerialize["inviteToken"] = o.InviteToken
	}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	if o.RememberMe != nil {
		toSerialize["rememberMe"] = o.RememberMe
	}
	if o.Username != nil {
		toSerialize["username"] = o.Username
	}
	return json.Marshal(toSerialize)
}

type NullableAuthenticateRequst struct {
	value *AuthenticateRequst
	isSet bool
}

func (v NullableAuthenticateRequst) Get() *AuthenticateRequst {
	return v.value
}

func (v *NullableAuthenticateRequst) Set(val *AuthenticateRequst) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticateRequst) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticateRequst) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticateRequst(val *AuthenticateRequst) *NullableAuthenticateRequst {
	return &NullableAuthenticateRequst{value: val, isSet: true}
}

func (v NullableAuthenticateRequst) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticateRequst) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


